version: '3'

services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    depends_on:
      - db
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    networks:
      - my-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - target:/var/lib/mysql
    networks:
      - my-network
volumes:
  target:

networks:
  my-network: